version: '2.1'
services:
  portainer:
    image: portainer/portainer
    container_name: portainer
    restart: always
    ports:
      - 8000:8000
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/portainer:/data
  homebridge:
    image: oznu/homebridge:latest
    container_name: homebridge
    restart: always
    network_mode: host
    environment:
      - TZ=America/Santiago
      - PGID=1000
      - PUID=1000
      - HOMEBRIDGE_CONFIG_UI=1
      - HOMEBRIDGE_CONFIG_UI_PORT=8080
    volumes:
      - ./.homebridge:/homebridge
  transmission:
    image: linuxserver/transmission
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Santiago
        #- TRANSMISSION_WEB_HOME=/combustion-release/ #optional
      - USER=nas #optional
      - PASS=media #optional
    volumes:
      - /home/hugo/.config/transmission-daemon:/config
      - /mnt/nas/downloads:/downloads
        #- path to watch folder:/watch
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped
  samba:
    image: dperson/samba:latest
    container_name: samba
    command: '-u "nas;media" -s "media;/media;yes;no;no;nas,nas,nas" -p'
    restart: unless-stopped
    stdin_open: true
    tty: true
    environment:
      - USERID=1000
    ports:
      - 139:130
      - 445:445
    volumes:
      - /mnt/nas:/media
      - /usr/share/zoneinfo/America/Santiago:/etc/localtime
  minidlna:
    image: vladgh/minidlna
    container_name: minidlna
    restart: unless-stopped
    network_mode: host
    volumes:
      - /mnt/nas/media:/media
    environment:
      - MINIDLNA_FRIENDLY_NAME= Ciel DLNA
      - MINIDLNA_MEDIA_DIR= /media

