version: '2.1'
services:
  samba:
    # Updated due to a documented bug in alpine linux https://gitlab.alpinelinux.org/alpine/aports/-/issues/12346
    container_name: samba
    image: dperson/samba:rpi
    environment:
      USERID: 1000
      GROUPID: 1001
      TZ: America/Santiago
    ports:
      - "139:139/tcp"
      - "445:445/tcp"
    restart: unless-stopped
    stdin_open: true
    tty: true
    volumes:
      - /mnt/nas:/media
    command: -u "nas;media" -s "media;/media;yes;no;no;nas;nas;nas"
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    command: -H unix:///var/run/docker.sock
    restart: always
    ports:
      - 8000:8000
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/portainer:/data
  transmission:
    image: linuxserver/transmission
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Santiago
        #- TRANSMISSION_WEB_HOME=/combustion-release/ #optional
      - USER=nas #optional
      - PASS=media #optional
    volumes:
      - ~/.config/transmission-daemon:/config
      - /mnt/nas/downloads:/downloads
        #- path to watch folder:/watch
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped
  minidlna:
    image: vladgh/minidlna
    container_name: minidlna
    restart: unless-stopped
    network_mode: host
    volumes:
      - /mnt/nas/media:/media
    environment:
      - MINIDLNA_FRIENDLY_NAME= Ciel DLNA
      - MINIDLNA_MEDIA_DIR= /media

